services:
  http-server-projeto-korp:
    build: .
    container_name: http-server-projeto-korp
    networks:
      - korp-network

  nginx:
    image: nginx:1.30.4
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /etc/korp-lab/nginx:/etc/nginx/conf.d
    networks:
      - korp-network
    depends_on:
      - http-server-projeto-korp

  prometheus:
    image: prom/prometheus:v3.13.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /etc/korp-lab/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - korp-network

  grafana:
    image: grafana/grafana:13.1.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /etc/korp-lab/grafana/provisioning:/etc/grafana/provisioning
      - /etc/korp-lab/grafana/dashboards:/etc/grafana/dashboards
    networks:
      - korp-network

networks:
  korp-network:
    external: true
