{
 "title": "Projeto Korp - Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disponibilidade do Serviço",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"http-server-projeto-korp\"}"
    }
   ]
  },
  {
   "title": "Total de Requisições Recebidas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "http_requests_total" }
   ]
  },
  {
   "title": "Volume de Requisições (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])" }
   ]
  }
 ]
}