---
- name: Create Grafana configuration and provisioning directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /etc/automated-observability-environment/grafana/provisioning/datasources
    - /etc/automated-observability-environment/grafana/provisioning/dashboards
    - /etc/automated-observability-environment/grafana/dashboards

- name: Copy Grafana configuration and dashboard files
  ansible.builtin.copy:
    src: "/opt/automated-observability-environment/grafana/{{ item }}"
    dest: "/etc/automated-observability-environment/grafana/{{ item }}"
    remote_src: true
    mode: "0644"
  loop:
    - provisioning/datasources/datasources.yaml
    - provisioning/dashboards/dashboards.yaml
    - dashboards/http-server-dashboard.json
