server {
    listen 80;

    location /projeto-korp {
        proxy_pass http://http-server-projeto-korp:8080/projeto-korp;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
