- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add vagrant user to docker group
  ansible.builtin.user:
    name: vagrant
    groups: docker
    append: true
