---
- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add deployment user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
