---
- name: Create Nginx configuration directory
  ansible.builtin.file:
    path: /etc/korp-lab/nginx
    state: directory
    mode: "0755"

- name: Configure Nginx reverse proxy
  ansible.builtin.copy:
    src: /opt/korp-lab/nginx/http-server-projeto-korp.conf
    dest: /etc/korp-lab/nginx/http-server-projeto-korp.conf
    remote_src: true
    mode: "0644"
