---
- name: Create Nginx configuration directory
  ansible.builtin.file:
    path: /etc/automated-observability-environment/nginx
    state: directory
    mode: "0755"

- name: Configure Nginx reverse proxy
  ansible.builtin.copy:
    src: /opt/automated-observability-environment/nginx/http-server.conf
    dest: /etc/automated-observability-environment/nginx/http-server.conf
    remote_src: true
    mode: "0644"
