---
- name: Provision the Korp Project Environment
  hosts: korp_lab
  become: true
  roles:
    - update-os
    - docker-install
    - docker-non-root
    - docker-network
    - clone-repository
    - nginx
    - prometheus
    - grafana
    - app
    - service-validation
