---
- name: Provision the Automated Observability Environment
  hosts: observability_environment
  become: true
  roles:
    - update-os
    - docker-install
    - docker-non-root
    - docker-network
    - clone-repository
    - nginx
    - prometheus
    - grafana
    - service-deploy
    - service-validation
