---
- name: Install git
  ansible.builtin.apt:
    name: git
    state: present

- name: Clone the Korp Lab repository
  ansible.builtin.git:
    repo: "https://github.com/thomaspalma1/korp-lab.git"
    dest: "/opt/korp-lab"
    version: main
    force: true

- name: Ensure repository ownership belongs to the deployment user
  ansible.builtin.file:
    path: "/opt/korp-lab"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true
